-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/
package.path = "/home/isurug/.config/hypr/?.lua;" .. package.path
local M = {}

require("monitors")
require("variables")
require("autostart")
-- require("env")
require("looks")
require("input")
require("binds")
-- require("windowrules")
