[main]
font=JetBrainsMono Nerd Font:size=18
terminal=kitty
prompt="❯ "
width=50
lines=10
tabs=4
horizontal-pad=15
vertical-pad=10
inner-pad=5
# Ensures it shows up over fullscreen games/apps
layer=top

[colors]
# Format: RRGGBBAA (The 'ff' at the end is 100% opacity)
background=0f1117bb
text=cbced3ff
match=e06c75ff
selection=56b6c2bb
selection-text=0f1117ff
selection-match=e06c75ff
border=56b6c2ff

[border]
width=2
radius=10
