-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/
package.path = "/home/isurug/.config/hypr/?.lua;" .. package.path
local M = {}

hl.config({
	["cursor.enable_hyprcursor"] = true,
})

hl.env("HYPRCURSOR_THEME", "Extracted Theme")
hl.env("HYPRCURSOR_SIZE", "32")

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "28")

require("autostart")
require("monitors")
require("variables")
-- require("env")
require("looks")
require("input")
require("binds")
require("windowrules")
